### ISSUE TITLE
Support orgs with more than 1000 ApexClasses in the default namespace.

### ISSUE THREAD

**Issue by ImJohnMDaniel** [afawcett/apex-umlcanvas#12]
The ApexClass selection list on the left sidebar will fail if there are more than 1000 ApexClasses in the default namespace of the org.

This is an issue with the apex:repeat because it can only contain 1000 records (see [VisualForce docs](www.salesforce.com/us/developer/docs/pages/Content/pages_compref_repeat.htm) )

**Comment by TedHusted** [comment]
@ImJohnMDaniel - If you wanted to bring out a beta, I could test #12. 

Or, if you are not available, should I deploy the source to a developer org with a different prefix, and roll a version that way?
