### ISSUE TITLE
Collection size XXXX exceeds maximum size of 1,000. 

### ISSUE THREAD

**Issue by msreekm** [afawcett/apex-umlcanvas#14]
My org has more that 1000 classes and the tool failed to start!
Visualforce Error
Help for this Page

Collection size 1,276 exceeds maximum size of 1,000.

**Comment by Condimenting** [comment]
@afawcett This is the issue that I was explaining over Twitter. 

I don't think it'd be wise for me to move forward using your project. One of the SFDC managers at my company graciously gave me a sandbox to play around with in my current role ( in an unrelated department), and an old install was left on the sandbox. When I asked some of the devs I'd be working with about the install, they said they weren't pleased with the code coverage and I got an odd look when I asked about forking the project. 

However, I do appreciate your prompt reply!

**Comment by afawcett** [comment]
@Condimenting thats no problem at all. Though btw, the code coverage of this tool has no implication on your sandbox code when you install through the managed package.

**Comment by afawcett** [comment]
Yes, the issue is here...

https://github.com/afawcett/apex-umlcanvas/blob/master/src/classes/ApexClassesSelector.cls#L53

If you have the skills to do so, add a WHERE clause to perhaps reduce the class list by those updated in the last year or with a certain name or prefix?

**Comment by afawcett** [comment]
This has been included in v1.7. @msreekm  if you are able to retry please give it a go. Having reviewed John's change it will for sure have resolved this error. If there is another issue we can open a new issue.

**Comment by msreekm** [comment]
@afawcett , I do not have access to that org anymore since I changed job . thanks for the fix.
