### ISSUE TITLE
INVALID_ARGUMENT_TYPE : Missing field [TableEnumOrId] on trigger create

### ISSUE THREAD

**Issue by raphym** [afawcett/apex-umlcanvas#18]
I _**Andrew**_ , 
I am using your class "ToolingAPI" to create a trigger dynamically , but i received the Error **"INVALID_ARGUMENT_TYPE : Missing field [TableEnumOrId] on trigger create"**

I am using this code : 
ToolingAPI toolingAPI = new ToolingAPI();
toolingAPI.ApexTrigger newTrigger = new ToolingAPI.ApexTrigger();
newTrigger.Name = 'HelloWorld77';
newTrigger.Body = 'trigger HelloWorld77 on Account (before insert) {}';

and when I added this line : 
newTrigger.tableEnumOrId = 'Account';
I received an another error :
**System.StringException: Invalid id: Account**

Thank you for your help @alan-morey @ImJohnMDaniel @afawcett 
_**Raphael**_

**Comment by afawcett** [comment]
Thanks for raising this @raphym 

Meanwhile change 'tableEnumOrId' to a String variable.

**Comment by raphym** [comment]
**_In conclusion the solution is:_**

In the class **ToolingAPI.cls change two things :**

1. 

`public Id tableEnumOrId; to public String tableEnumOrId;
`

2. 

`jsonGen.writeIdField('tableEnumOrId', tableEnumOrId); to                    jsonGen.writeStringField('tableEnumOrId', tableEnumOrId);`

And of course you can know use it here :

    ToolingAPI toolingAPI = new ToolingAPI();
    toolingAPI.ApexTrigger newTrigger = new ToolingAPI.ApexTrigger();
    newTrigger.Name = 'HelloWorld77';
    newTrigger.Body = 'trigger HelloWorld77 on Account (before insert) {}';
    newTrigger.tableEnumOrId='Account';
    toolingAPI.createSObject(newTrigger);


Thank you @afawcett 

**_Raphael_**

**Comment by afawcett** [comment]
Excellent, @raphym thanks for sharing! 👍
