### ISSUE TITLE
Getting error when select class "Cannot set property 'symbolTable' of undefined"

### ISSUE THREAD

**Issue by santoshkumbar** [afawcett/apex-umlcanvas#19]
Installed V1.5 on sandbox and tried to select a class and not seeing any response after that. 
Chrome Console showing following error : 
1> Uncaught TypeError: Cannot read property 'name' of null
    at Object.constructUMLClass (uml?sfdc.tabName=01rQ0000000Djvr:262)
    at Visualforce.remoting.Manager.invokeAction.escape (uml?sfdc.tabName=01rQ0000000Djvr:108)
    at e.cb (VFRemote.js:133)
    at constructor.doCallback (VFRemote.js:99)
    at constructor.onData (VFRemote.js:94)
    at VFExt3.data.Connection.handleResponse (VFRemote.js:75)
    at a (VFRemote.js:39)
    at VFRemote.js:40
constructUMLClass @ uml?sfdc.tabName=01rQ0000000Djvr:262
Visualforce.remoting.Manager.invokeAction.escape @ uml?sfdc.tabName=01rQ0000000Djvr:108
e.cb @ VFRemote.js:133
doCallback @ VFRemote.js:99
onData @ VFRemote.js:94
handleResponse @ VFRemote.js:75
a @ VFRemote.js:39
(anonymous) @ VFRemote.js:40
setInterval (async)
g @ VFRemote.js:40
request @ VFRemote.js:42
request @ VFRemote.js:74
doSend @ VFRemote.js:96
combineAndSend @ VFRemote.js:96
g @ VFRemote.js:79
setInterval (async)
b.delay @ VFRemote.js:79
queueTransaction @ VFRemote.js:127
doCall @ VFRemote.js:97
doCall @ VFRemote.js:127
(anonymous) @ VFRemote.js:99
(anonymous) @ VFRemote.js:18
invokeAction @ VFRemote.js:138
select @ uml?sfdc.tabName=01rQ0000000Djvr:99
onclick @ uml?sfdc.tabName=01rQ0000000Djvr:332
uml?sfdc.tabName=01rQ0000000Djvr:201 

2. > 

Uncaught TypeError: Cannot set property 'symbolTable' of undefined
    at Visualforce.remoting.Manager.invokeAction.escape (uml?sfdc.tabName=01rQ0000000Djvr:201)
    at e.cb (VFRemote.js:133)
    at constructor.doCallback (VFRemote.js:99)
    at constructor.onData (VFRemote.js:94)
    at VFExt3.data.Connection.handleResponse (VFRemote.js:75)
    at a (VFRemote.js:39)
    at VFRemote.js:40
Visualforce.remoting.Manager.invokeAction.escape @ uml?sfdc.tabName=01rQ0000000Djvr:201
e.cb @ VFRemote.js:133
doCallback @ VFRemote.js:99
onData @ VFRemote.js:94
handleResponse @ VFRemote.js:75
a @ VFRemote.js:39
(anonymous) @ VFRemote.js:40
setInterval (async)
g @ VFRemote.js:40
request @ VFRemote.js:42
request @ VFRemote.js:74
doSend @ VFRemote.js:96
combineAndSend @ VFRemote.js:96
g @ VFRemote.js:79
setInterval (async)
b.delay @ VFRemote.js:79
queueTransaction @ VFRemote.js:127
doCall @ VFRemote.js:97
doCall @ VFRemote.js:127
(anonymous) @ VFRemote.js:99
(anonymous) @ VFRemote.js:18
invokeAction @ VFRemote.js:138
renderRelationships @ uml?sfdc.tabName=01rQ0000000Djvr:190
Visualforce.remoting.Manager.invokeAction.escape @ uml?sfdc.tabName=01rQ0000000Djvr:159
e.cb @ VFRemote.js:133
doCallback @ VFRemote.js:99
onData @ VFRemote.js:94
handleResponse @ VFRemote.js:75
a @ VFRemote.js:39
(anonymous) @ VFRemote.js:40
setInterval (async)
g @ VFRemote.js:40
request @ VFRemote.js:42
request @ VFRemote.js:74
doSend @ VFRemote.js:96
combineAndSend @ VFRemote.js:96
g @ VFRemote.js:79
setInterval (async)
b.delay @ VFRemote.js:79
queueTransaction @ VFRemote.js:127
doCall @ VFRemote.js:97
doCall @ VFRemote.js:127
(anonymous) @ VFRemote.js:99
(anonymous) @ VFRemote.js:18
invokeAction @ VFRemote.js:138
checkAsync @ uml?sfdc.tabName=01rQ0000000Djvr:144
setInterval (async)
Visualforce.remoting.Manager.invokeAction.escape @ uml?sfdc.tabName=01rQ0000000Djvr:79
e.cb @ VFRemote.js:133
doCallback @ VFRemote.js:99
onData @ VFRemote.js:94
handleResponse @ VFRemote.js:75
a @ VFRemote.js:39
(anonymous) @ VFRemote.js:40
setInterval (async)
g @ VFRemote.js:40
request @ VFRemote.js:42
request @ VFRemote.js:74
doSend @ VFRemote.js:96
combineAndSend @ VFRemote.js:96
g @ VFRemote.js:79
setInterval (async)
b.delay @ VFRemote.js:79
queueTransaction @ VFRemote.js:127
doCall @ VFRemote.js:97
doCall @ VFRemote.js:127
(anonymous) @ VFRemote.js:99
(anonymous) @ VFRemote.js:18
invokeAction @ VFRemote.js:138
select @ uml?sfdc.tabName=01rQ0000000Djvr:99
onclick @ uml?sfdc.tabName=01rQ0000000Djvr:332

**Comment by afawcett** [comment]
Do you have any managed packages installed in your org?

**Comment by afawcett** [comment]
I just noticed this when developing v1.7 and made a fix. It looks to be a change to the SF TOoling API since the tool was written. I've made a change that should fix it. Please try v1.7 and let me know.

**Comment by afawcett** [comment]
We can re-open this if its still an issue. But based on the stack traces above it is identical to the issue i just fixed in v1.7.
