### ISSUE TITLE
Getting “Bad id ” when selecting a class, even after adding remote site settings

### ISSUE THREAD

**Issue by prolayc** [afawcett/apex-umlcanvas#20]
I am getting the bad id error on different lines. I added the remote site and also compiled all the classes.

![badid-error-apex-canva](https://user-images.githubusercontent.com/5306583/45926626-e2e1dd80-bf42-11e8-92ed-3fe76298df80.PNG)

**Comment by prolayc** [comment]
I am still looking for the solution.

**Comment by afawcett** [comment]
This has been fixed in v1.7. Seemed to be a change in the Tooling API from what i could tell. I made a workaround in the code to tolerate the change.
