### ISSUE TITLE
Better message needed prompting admin to setup Remote Site Setting for ApexUML

### ISSUE THREAD

**Issue by ImJohnMDaniel** [afawcett/apex-umlcanvas#6]
When ApexUML is installed, the usual experience is that the admin forgets to add a Remote Site Setting record to allow ApexUML to utilize the connection to the ToolingAPI.   (I know I keep forgetting).  Right now the exception comes back as very convoluted and is not a "user friendly" message explaining what needs to be done.  We can do better!!!  ;-)

**Comment by afawcett** [comment]
This has been included in v1.7.
